### ISSUE TITLE
SSEEdit Undeclared Identifier 'FileFormID'

### ISSUE THREAD

**Issue by Saizetsu** [fireundubh/WryeBashTagGenerator#2]
It throws an issue on line 292 whenever I try to run it on Dawnguard.esm

This is with xedit version 4.0.3g and 4.1.3g
[SSEEditException.log](https://github.com/fireundubh/WryeBashTagGenerator/files/6749898/SSEEditException.log)

**Comment by fireundubh** [comment]
Thanks for the report! Fixed in https://github.com/fireundubh/WryeBashTagGenerator/commit/8d8b795f5dd5fb4c3ee14562f35c8149bf4edc20.
